--liquibase formatted sql
--changeset hr-db:001-create-table-lb-demo-orders

CREATE TABLE LB_DEMO_ORDERS (
  ORDER_ID        NUMBER(10)       NOT NULL,
  CUSTOMER_NAME   VARCHAR2(100)    NOT NULL,
  ORDER_STATUS    VARCHAR2(20)     DEFAULT 'NEW' NOT NULL,
  ORDER_TOTAL     NUMBER(12,2)     DEFAULT 0 NOT NULL,
  CREATED_AT      DATE             DEFAULT SYSDATE NOT NULL,
  CONSTRAINT LB_DEMO_ORDERS_PK PRIMARY KEY (ORDER_ID),
  CONSTRAINT LB_DEMO_ORDERS_STATUS_CHK CHECK (ORDER_STATUS IN ('NEW','PAID','CANCELLED'))
);