--liquibase formatted sql
--changeset hr-db:002-create-table-lb-demo-customers

CREATE TABLE LB_DEMO_CUSTOMERS (
  CUSTOMER_ID      NUMBER(10)      NOT NULL,
  CUSTOMER_NAME    VARCHAR2(120)   NOT NULL,
  EMAIL            VARCHAR2(180)   NOT NULL,
  PHONE_NUMBER     VARCHAR2(30),
  CREATED_AT       DATE            DEFAULT SYSDATE NOT NULL,
  CONSTRAINT LB_DEMO_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT LB_DEMO_CUSTOMERS_EMAIL_UK UNIQUE (EMAIL)
);
