--liquibase formatted sql
--changeset hr-db:003-insert-lb-demo-orders

INSERT INTO LB_DEMO_ORDERS (ORDER_ID, CUSTOMER_NAME, ORDER_STATUS, ORDER_TOTAL)
VALUES (1005, 'Emma Brown', 'NEW', 999.00);

INSERT INTO LB_DEMO_ORDERS (ORDER_ID, CUSTOMER_NAME, ORDER_STATUS, ORDER_TOTAL)
VALUES (1006, 'Noah Taylor', 'CANCELLED', 120.00);

INSERT INTO LB_DEMO_ORDERS (ORDER_ID, CUSTOMER_NAME, ORDER_STATUS, ORDER_TOTAL)
VALUES (1007, 'Olivia Martin', 'PAID', 749.40);
